# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    build:
      dockerfile: Dockerfile-postgis
      context: ./
    restart: always
    environment:
      name: edric
      POSTGRES_PASSWORD: example

  web:
    build:
      dockerfile: Dockerfile-web
      context: ./
    restart: always
    environment:
      CFM_DB: CFM6_preferred_db 
      CFM_DATASET: CFM6_PREFERRED
      CFM_BTN_LABEL: ALT
      CFM_DB_PORT: 8086 
    ports:
      - 8082:8081
      - 8083:80

  altweb:
    build:
      dockerfile: Dockerfile-web
      context: ./
    restart: always
    environment:
      CFM_DB: CFM6_alt_db 
      CFM_DATASET: CFM6_ALTERNATIVE
      CFM_BTN_LABEL: MAIN 
      CFM_DB_PORT: 8082 
    ports:
      - 8086:8081
      - 8087:80

