FROM amazonlinux

WORKDIR /app

COPY . /app

RUN yum install -y httpd && \
	amazon-linux-extras install -y php7.2 && \
	yum install -y php php-pgsql 

COPY ./doc/cfm.conf /etc/httpd/conf.d/
COPY ./custom-php.ini /etc/php.d/custom-php.ini

## link the web/php/util.php
COPY ./web/php/util_preferred.php /app/web/php/util.php
COPY ./web/viewer_preferred.php /app/web/index.php

CMD ["apachectl", "-D", "FOREGROUND"]

